### ISSUE TITLE
Update ktor to 0.9.2

### ISSUE THREAD

**Issue by AndreasVolkmann** [goreRatzete/realworld-kotlin-ktor#10]
The new release contains the new auth api

**Comment by ninrod** [comment]
Hi, wonderful work. I'm trying to generate jwt tokens through ktor. But I don't get it. What seemed to be the problem up until ktor 0.9.2? is ktor ready to generate jwt tokens now? 

thanks again for your work.

**Comment by AndreasVolkmann** [comment]
@ninrod I replied to you on slack. 
Here is the comment in case someone else has a similar question:

When you `compile "io.ktor:ktor-auth-jwt:$ktor_version"`, you also get `com.auth0:java-jwt`.

Then you just use `JWT.create()`.

Full example can be found here: https://github.com/AndreasVolkmann/ktor-auth-jwt-sample/blob/master/src/main/kotlin/me/avo/io/ktor/auth/jwt/sample/JwtConfig.kt

**Comment by ninrod** [comment]
@AndreasVolkmann, thank you! So is kotlin ready to deal with everything that is required for a "realword" app submission?

**Comment by AndreasVolkmann** [comment]
@ninrod Yes I think so. All the previous issues should have been resolved.

**Comment by ninrod** [comment]
Nice. I'm already using your sample [project](https://github.com/AndreasVolkmann/ktor-auth-jwt-sample) to study jwt with ktor and it has been very helpful so far, good work.
