### ISSUE TITLE
Do you think to continue?

### ISSUE THREAD

**Issue by Rudge** [goreRatzete/realworld-kotlin-ktor#11]
Hi, I found your repo now but previously I was creating one [repo](https://github.com/Rudge/kotlin-ktor-realworld-example-app) that use the same structure of my other project with [Javalin](https://github.com/Rudge/kotlin-javalin-realworld-example-app), I was thinking that if you will continue with this repo, we could do a merge the projects. But if you don't think more to update the repo, I will continue with my repo.

What do you thing?

Thanks.

**Comment by AndreasVolkmann** [comment]
Hi @Rudge .

I am currently no longer working on this. 
In case of a merge would you want to go with Javalin or Ktor ?

**Comment by Rudge** [comment]
I finished the Javalin and now I was working in the Ktor version. My doubt is if I keep going with my Ktor repo or I update yours.

 What do you think?

**Comment by AndreasVolkmann** [comment]
@Rudge IMO it makes more sense to create a new one, since I started this a long time ago. 
But you can take this one over, if you want, seeing as it already has some exposure.

Essentially you only have to update the server and routing logic from your javalin example and it should work.
